/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BotPayment__factory } from "./BotPayment__factory";
export { FireCoin__factory } from "./FireCoin__factory";
