/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace BotPayment {
  export type PaymentStruct = {
    from: AddressLike;
    to: AddressLike;
    amount: BigNumberish;
    feeAmount: BigNumberish;
    timestamp: BigNumberish;
    service: string;
    completed: boolean;
  };

  export type PaymentStructOutput = [
    from: string,
    to: string,
    amount: bigint,
    feeAmount: bigint,
    timestamp: bigint,
    service: string,
    completed: boolean
  ] & {
    from: string;
    to: string;
    amount: bigint;
    feeAmount: bigint;
    timestamp: bigint;
    service: string;
    completed: boolean;
  };
}

export interface BotPaymentInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_FEE"
      | "botBalances"
      | "deposit"
      | "feeCollector"
      | "feePercentage"
      | "fireCoin"
      | "getBotBalance"
      | "getPayment"
      | "owner"
      | "payBot"
      | "paymentCount"
      | "payments"
      | "quickPay"
      | "registerBot"
      | "registeredBots"
      | "renounceOwnership"
      | "setFeeCollector"
      | "setFeePercentage"
      | "transferOwnership"
      | "unregisterBot"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BotRegistered"
      | "BotUnregistered"
      | "Deposit"
      | "FeeCollected"
      | "FeePercentageUpdated"
      | "OwnershipTransferred"
      | "PaymentCompleted"
      | "PaymentCreated"
      | "Withdrawal"
  ): EventFragment;

  encodeFunctionData(functionFragment: "MAX_FEE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "botBalances",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "feeCollector",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "feePercentage",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "fireCoin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getBotBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPayment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payBot",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "paymentCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "payments",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "quickPay",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerBot",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registeredBots",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeCollector",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeePercentage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unregisterBot",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "MAX_FEE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "botBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "feeCollector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feePercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fireCoin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBotBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPayment", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "payBot", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymentCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "payments", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "quickPay", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerBot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registeredBots",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeCollector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeePercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unregisterBot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace BotRegisteredEvent {
  export type InputTuple = [bot: AddressLike];
  export type OutputTuple = [bot: string];
  export interface OutputObject {
    bot: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BotUnregisteredEvent {
  export type InputTuple = [bot: AddressLike];
  export type OutputTuple = [bot: string];
  export interface OutputObject {
    bot: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositEvent {
  export type InputTuple = [bot: AddressLike, amount: BigNumberish];
  export type OutputTuple = [bot: string, amount: bigint];
  export interface OutputObject {
    bot: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeCollectedEvent {
  export type InputTuple = [collector: AddressLike, amount: BigNumberish];
  export type OutputTuple = [collector: string, amount: bigint];
  export interface OutputObject {
    collector: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeePercentageUpdatedEvent {
  export type InputTuple = [newFee: BigNumberish];
  export type OutputTuple = [newFee: bigint];
  export interface OutputObject {
    newFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentCompletedEvent {
  export type InputTuple = [paymentId: BigNumberish];
  export type OutputTuple = [paymentId: bigint];
  export interface OutputObject {
    paymentId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentCreatedEvent {
  export type InputTuple = [
    paymentId: BigNumberish,
    from: AddressLike,
    to: AddressLike,
    amount: BigNumberish,
    fee: BigNumberish,
    service: string
  ];
  export type OutputTuple = [
    paymentId: bigint,
    from: string,
    to: string,
    amount: bigint,
    fee: bigint,
    service: string
  ];
  export interface OutputObject {
    paymentId: bigint;
    from: string;
    to: string;
    amount: bigint;
    fee: bigint;
    service: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalEvent {
  export type InputTuple = [bot: AddressLike, amount: BigNumberish];
  export type OutputTuple = [bot: string, amount: bigint];
  export interface OutputObject {
    bot: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BotPayment extends BaseContract {
  connect(runner?: ContractRunner | null): BotPayment;
  waitForDeployment(): Promise<this>;

  interface: BotPaymentInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_FEE: TypedContractMethod<[], [bigint], "view">;

  botBalances: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  deposit: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  feeCollector: TypedContractMethod<[], [string], "view">;

  feePercentage: TypedContractMethod<[], [bigint], "view">;

  fireCoin: TypedContractMethod<[], [string], "view">;

  getBotBalance: TypedContractMethod<[bot: AddressLike], [bigint], "view">;

  getPayment: TypedContractMethod<
    [paymentId: BigNumberish],
    [BotPayment.PaymentStructOutput],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  payBot: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish, service: string],
    [bigint],
    "nonpayable"
  >;

  paymentCount: TypedContractMethod<[], [bigint], "view">;

  payments: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, string, boolean] & {
        from: string;
        to: string;
        amount: bigint;
        feeAmount: bigint;
        timestamp: bigint;
        service: string;
        completed: boolean;
      }
    ],
    "view"
  >;

  quickPay: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish, service: string],
    [bigint],
    "nonpayable"
  >;

  registerBot: TypedContractMethod<[bot: AddressLike], [void], "nonpayable">;

  registeredBots: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setFeeCollector: TypedContractMethod<
    [_feeCollector: AddressLike],
    [void],
    "nonpayable"
  >;

  setFeePercentage: TypedContractMethod<
    [_feePercentage: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unregisterBot: TypedContractMethod<[bot: AddressLike], [void], "nonpayable">;

  withdraw: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "botBalances"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "feeCollector"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "feePercentage"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "fireCoin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getBotBalance"
  ): TypedContractMethod<[bot: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPayment"
  ): TypedContractMethod<
    [paymentId: BigNumberish],
    [BotPayment.PaymentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "payBot"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish, service: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "paymentCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "payments"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, string, boolean] & {
        from: string;
        to: string;
        amount: bigint;
        feeAmount: bigint;
        timestamp: bigint;
        service: string;
        completed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "quickPay"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish, service: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerBot"
  ): TypedContractMethod<[bot: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registeredBots"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFeeCollector"
  ): TypedContractMethod<[_feeCollector: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFeePercentage"
  ): TypedContractMethod<[_feePercentage: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unregisterBot"
  ): TypedContractMethod<[bot: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "BotRegistered"
  ): TypedContractEvent<
    BotRegisteredEvent.InputTuple,
    BotRegisteredEvent.OutputTuple,
    BotRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "BotUnregistered"
  ): TypedContractEvent<
    BotUnregisteredEvent.InputTuple,
    BotUnregisteredEvent.OutputTuple,
    BotUnregisteredEvent.OutputObject
  >;
  getEvent(
    key: "Deposit"
  ): TypedContractEvent<
    DepositEvent.InputTuple,
    DepositEvent.OutputTuple,
    DepositEvent.OutputObject
  >;
  getEvent(
    key: "FeeCollected"
  ): TypedContractEvent<
    FeeCollectedEvent.InputTuple,
    FeeCollectedEvent.OutputTuple,
    FeeCollectedEvent.OutputObject
  >;
  getEvent(
    key: "FeePercentageUpdated"
  ): TypedContractEvent<
    FeePercentageUpdatedEvent.InputTuple,
    FeePercentageUpdatedEvent.OutputTuple,
    FeePercentageUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PaymentCompleted"
  ): TypedContractEvent<
    PaymentCompletedEvent.InputTuple,
    PaymentCompletedEvent.OutputTuple,
    PaymentCompletedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentCreated"
  ): TypedContractEvent<
    PaymentCreatedEvent.InputTuple,
    PaymentCreatedEvent.OutputTuple,
    PaymentCreatedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawal"
  ): TypedContractEvent<
    WithdrawalEvent.InputTuple,
    WithdrawalEvent.OutputTuple,
    WithdrawalEvent.OutputObject
  >;

  filters: {
    "BotRegistered(address)": TypedContractEvent<
      BotRegisteredEvent.InputTuple,
      BotRegisteredEvent.OutputTuple,
      BotRegisteredEvent.OutputObject
    >;
    BotRegistered: TypedContractEvent<
      BotRegisteredEvent.InputTuple,
      BotRegisteredEvent.OutputTuple,
      BotRegisteredEvent.OutputObject
    >;

    "BotUnregistered(address)": TypedContractEvent<
      BotUnregisteredEvent.InputTuple,
      BotUnregisteredEvent.OutputTuple,
      BotUnregisteredEvent.OutputObject
    >;
    BotUnregistered: TypedContractEvent<
      BotUnregisteredEvent.InputTuple,
      BotUnregisteredEvent.OutputTuple,
      BotUnregisteredEvent.OutputObject
    >;

    "Deposit(address,uint256)": TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;
    Deposit: TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;

    "FeeCollected(address,uint256)": TypedContractEvent<
      FeeCollectedEvent.InputTuple,
      FeeCollectedEvent.OutputTuple,
      FeeCollectedEvent.OutputObject
    >;
    FeeCollected: TypedContractEvent<
      FeeCollectedEvent.InputTuple,
      FeeCollectedEvent.OutputTuple,
      FeeCollectedEvent.OutputObject
    >;

    "FeePercentageUpdated(uint256)": TypedContractEvent<
      FeePercentageUpdatedEvent.InputTuple,
      FeePercentageUpdatedEvent.OutputTuple,
      FeePercentageUpdatedEvent.OutputObject
    >;
    FeePercentageUpdated: TypedContractEvent<
      FeePercentageUpdatedEvent.InputTuple,
      FeePercentageUpdatedEvent.OutputTuple,
      FeePercentageUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PaymentCompleted(uint256)": TypedContractEvent<
      PaymentCompletedEvent.InputTuple,
      PaymentCompletedEvent.OutputTuple,
      PaymentCompletedEvent.OutputObject
    >;
    PaymentCompleted: TypedContractEvent<
      PaymentCompletedEvent.InputTuple,
      PaymentCompletedEvent.OutputTuple,
      PaymentCompletedEvent.OutputObject
    >;

    "PaymentCreated(uint256,address,address,uint256,uint256,string)": TypedContractEvent<
      PaymentCreatedEvent.InputTuple,
      PaymentCreatedEvent.OutputTuple,
      PaymentCreatedEvent.OutputObject
    >;
    PaymentCreated: TypedContractEvent<
      PaymentCreatedEvent.InputTuple,
      PaymentCreatedEvent.OutputTuple,
      PaymentCreatedEvent.OutputObject
    >;

    "Withdrawal(address,uint256)": TypedContractEvent<
      WithdrawalEvent.InputTuple,
      WithdrawalEvent.OutputTuple,
      WithdrawalEvent.OutputObject
    >;
    Withdrawal: TypedContractEvent<
      WithdrawalEvent.InputTuple,
      WithdrawalEvent.OutputTuple,
      WithdrawalEvent.OutputObject
    >;
  };
}
