/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BotPayment } from "./BotPayment";
export type { FCOINAuction } from "./FCOINAuction";
export type { FireCoin } from "./FireCoin";
export type { FireCoinPG } from "./FireCoinPG";
export type { WrappedFireCoin } from "./WrappedFireCoin";
